### ISSUE TITLE
VaultAPI using old Bukkit API version?

### ISSUE THREAD

**Issue by Altruiis** [MilkBowl/VaultAPI#106]
Using the VaultAPI with Maven seems to use Bukkit 1.13. After putting it in my pom.xml, my project tried to use the 1.13 api for everything, breaking my plugin. Removing vault and anything related to it in the code and from the pom.xml fixed it, and it went back to using paper 1.16.5. Sorry if this issue is not descriptive enough, but that's the error.

Reproducing:
1. Add paper dependency and repository to pom.xml
2. Write some code
3. Add vault api to pom.xml
4. The project will switch back to 1.13, removing the ability to use any methods from 1.16 (such as the sendActionBar method) as well as any materials e.g. NETHER_GOLD_ORE.
5. Removing the vault api fixes it.

**Comment by Sleaker** [comment]
Sounds like you're not declaring your dependencies properly, or you're building against something that might be incompatible. I don't have plans to build against Paper since paper is a different API as a whole. you can try setting up your project so it doesn't try to pull in transitive dependencies but I haven't looked into maven resolvers in a long time so you'd need to check into how to fix that.
