### ISSUE TITLE
the return type is wrong

### ISSUE THREAD

**Issue by Propromp** [MilkBowl/VaultAPI#108]
the return type of Economy#bankHas(String name, double amount) is wrong.
It should be Boolean, but it's actually EconomyResponce.

**Comment by Sleaker** [comment]
It's not 'the wrong type' - Economy operations return a wrapped response via https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/EconomyResponse.java because not all economies support all operations, so you have to unwrap the response to see if A) the economy even supports the operation and B) if the operation returned a success or not. The original comment on the doc says it returns true or false, but this was altered a long time ago, it's referring to SUCCESS/FAILURE of the EconomyResponse.

ResponseType should be SUCCESS if the operation was true, and FAILURE if it was false. see: https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/economy/plugins/Economy_Craftconomy3.java#L164 as an example.
