### ISSUE TITLE
Get the weight from a Group

### ISSUE THREAD

**Issue by blockiyt** [MilkBowl/VaultAPI#110]
Hi, I am coding a NameTagPlugin for our server and I want to integrate Vault. The problem is I can't find a way to get the weight from group so that I can sort the players in the Tablist. Could you help me with that?
Thank!

**Comment by Sleaker** [comment]
Vault doesn't have a concept such as group weights because those are permission-system specific things. Vault exposes a primary group via: https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/permission/Permission.java#L678 - but anything more advanced than this will require integrating with a specific permission system of your choice rather than a more generic API like Vault.
