### ISSUE TITLE
Vault Decimal Issue

### ISSUE THREAD

**Issue by rishabhk571** [MilkBowl/VaultAPI#148]
Hey, I need help with my currency getting beyond 2 decimal places, it's like 48.9999999999, how to fix it?

**Comment by Geolykt** [comment]
If your plugin is responsible for storing the economy, then you'd need to properly implement [Economy#format](https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java#L62), if your plugin displays this value, then use that method instead of formatting the balance yourself. If a foreign plugin is responsible for displaying the string and you are indeed implementing that method correctly then report it to the foreign plugin

**Comment by rishabhk571** [comment]
Lol, i just used vault economy fixed placeholder and it worked
