### ISSUE TITLE
Maven issues?

### ISSUE THREAD

**Issue by Locknlol** [MilkBowl/VaultAPI#26]
"The import net.milkbowl cannot be resolved"

I have switched to the maven repo below, while previously using [@TheE](https://github.com/MilkBowl/VaultAPI/issues/24) repo. I see that VaultAPI-1.6.jar is in my Maven Dependencies folder inside Eclipse, but I am unable to import anything from it.

```
    <repositories>
        <repository>
            <id>vault-repo</id>
            <url>http://nexus.hc.to/content/repositories/pub_releases</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>net.milkbowl.vault</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.6</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

**Comment by Sleaker** [comment]
Sorry, I'm not able to help with this maven issue. Vault main uses maven to build and requires VaultAPI to be available at the same version you're listing so I know it's working when it's being built on travis-ci, otherwise Vault wouldn't build properly.  Maybe you need to clear your maven cache/local repository to fix something due to switching the repos?

**Comment by Locknlol** [comment]
This resolved my issue, thanks!

**Comment by Sleaker** [comment]
@Locknlol - Awesome! glad it's working now.

**Comment by Locknlol** [comment]
... I forgot to install Essentials... I'm an idiot.
