### ISSUE TITLE
Everything deprecated??

### ISSUE THREAD

**Issue by ajgeiss0702** [MilkBowl/VaultAPI#30]
Everything that I have tried (depositing) are all deprecated. Is there something else i should use?

**Comment by Sleaker** [comment]
Maybe you're not accessing the correct methods. If you look through the reference it's pretty clear what methods are deprecated and which aren't https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java

most likely it's because you're not using OfflinePlayer objects.
