### ISSUE TITLE
Repo offline?

### ISSUE THREAD

**Issue by stuntguy3000** [MilkBowl/VaultAPI#31]
Hi,

I am receiving a connection issue. Is this a server issue?

**Comment by NorbiPeti** [comment]
It looks like it is. I get 502 Bad Gateway both from Maven and if I open it from a browser. In the case this wouldn't get fixed in the near future by any chance, for a workaround one can use jitpack.io to create a Maven dependency for this GitHub repository (repository: https://jitpack.io; groupId: com.github.milkbowl.vault; artifactId: VaultAPI; version: master-SNAPSHOT).

**Comment by Sleaker** [comment]
The webserver blew up last night, we're investigating nginx issues.

**Comment by TaylerNest** [comment]
It seems like repo offline AGAIN. What the...

**Comment by stuntguy3000** [comment]
As usual.

**Comment by Foorack** [comment]
Seems like repo is back. Functioning normal for me.

**Comment by BlackBeltPanda** [comment]
Down for me at the moment.

**Comment by stuntguy3000** [comment]
![image](https://cloud.githubusercontent.com/assets/1522389/23337725/bc0bc8bc-fc46-11e6-8937-51e41c346073.png)
