### ISSUE TITLE
Add Bungeecord support

### ISSUE THREAD

**Issue by Phoenix616** [MilkBowl/VaultAPI#39]
In this day and age a lot of general management plugins run on Bungeecord too. Especially permissions plugins, chat plugins and ban plugins are often seen running on BungeeCord networks with no common API for use of other plugins. Vault managed to provide this for Bukkit in the past, it would just feel right to also have a familiar for Bungee too.

**Comment by Sleaker** [comment]
Bungeecord is multi-server. Vault is just a server adapter directly. there's no work here. Ask your specific permission/economy plugin to support multi-server through a shared dataset.

**Comment by Phoenix616** [comment]
That's not what this issue is about. It's about bringing Vault to BungeeCord so you can use a similar interface with Bungee plugins as you can do with Bukkit plugins.

**Comment by Sleaker** [comment]
Bungeecord itself doesn't have the necessary API to facilitate this. note: Vault uses bukkit internals so that consumers don't inherently access Vault to get access to a provider. Vault simply provides a template of what methods are available universally.  Bungee doesn't have the services API, so Vault can't run on it.. ever. And there's no good way to work around this to force economy plugins to universally talk.

**Comment by Phoenix616** [comment]
There is a simple solution for that: Make Vault provide a services API on BungeeCord. (Or get a services API into BungeeCord itself)
