### ISSUE TITLE
references to deprecated methods / deprecated methods need to implement

### ISSUE THREAD

**Issue by Lingo93** [MilkBowl/VaultAPI#45]
The method playerHas(String, OfflinePlayer, String) refers to deprecated playerHas(String, String, String) method.
There is no alternative method to cleanly  implement an custom permission system.
In addition, this deprecated (abstract) method must be implemented.

**Comment by Sleaker** [comment]
@Lingo93 - I think you're missing something: https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/permission/Permission.java#L128

- The deprecated methods are for plugins that utilize the permission API so that they understand that some functionality is deprected and may produce incorrect/bad results or is unmaintained. I'm not sure why you think there's no way to cleanly implement something...

**Comment by Lingo93** [comment]
I want to implement vault support for an currently not supported permission system.

**Comment by Sleaker** [comment]
I really don't understand what you're getting at. override the methods that call back to deprecated functionality. It's deprecated in the base permission system to prevent consumers from continuing to use it or using it at their own risk.
