### ISSUE TITLE
Does VaultAPI plan to get get updated to 1.13?

### ISSUE THREAD

**Issue by wherkamp** [MilkBowl/VaultAPI#56]
I was looking through the source and I found a lot of things that would break in 1.13. I am wondering if vault plans to get updated?

**Comment by fahlur** [comment]
it doesnt like 1.13 at all xD the item class alone has over 100 errors because of the enum changes

**Comment by Banbeucmas** [comment]
It is already compatible even when 1.13 haven't came out lol.
The only thing worries is that all of the plugin that Vault use to provide API and stuff

**Comment by Sleaker** [comment]
@Banbeucmas - not completely true. I believe the entire item API is invalid at this point. The Item stuff is probably getting dumped due to this.

**Comment by DoNotSpamPls** [comment]
Why is it invalid? It seems to be using the Material API, what exactly is broken?

**Comment by treydun** [comment]
@DoNotSpamPls It does not have "api-version: 1.13" in its plugin.yml so spigot is providing a backwards compatible Material API. It does not include the items added in 1.13 (and has a few other unexpected issues). Once you add the api-version: 1.13 tag, spigot no longer supports a legacy Materials API and instead forces you into the new Materials api. Things do break in that transition :/ Currently Items.itemByString(ItemName) is not returning reliable results for many items including ones added in previous versions. Material.END_CRYSTAL/Material.ENDER_CRYSTAL is one off the top of my head. The bigger issues between 1.12 and 1.13 come into some of the flattening changes. https://minecraft.gamepedia.com/1.13/Flattening Items being split into multiple classes instead of a single class with damage values. Items.itemByString("white_wool") returns "Legacy Wool" because of vault not having the 1.13 api tag in the plugin.yml. Its really an issue of consistancy for plugins that are trying to be 1.13 compatible on things like items and names then having VaultAPI returning 'legacy items' or not recognizing an item by either its 1.12 or 1.13 direct minecraft/spigot Material name. Dont get me started on the switch from Head Material to {Skeleton Skull, Wither Skeleton Skull, Zombie Head, Player Head, Creeper Head, Dragon Head, Skeleton Wall Skull, Wither Skeleton Wall Skull, Zombie Wall Head, Player Wall Head, Creeper Wall Head, Dragon Wall Head} Its a messy transition and fairly difficult to maintain backwards version compatibility. (Just the fact that half of them refer to it as head and half a skull is infuriating enough, but that's mojangs naming convention. Spigot is just being more aligned with the minecraft codebase)

**Comment by woutwoot** [comment]
@treydun Although I agree remaining compatible with multiple versions is quite hard, I do think that the new naming is a good thing. It now all perfectly maps onto Minecraft item id's and finally gets rid of data values. For my shop plugin, this is causing me a lot of work, but at the same time, things will be way cleaner after I manage to update everything.

**Comment by treydun** [comment]
@woutwoot I didn't mean to come off as complaining. I also feel the change of Material names in bukkit to match the official Minecraft names is awesome. I was mostly trying to explain what would need to be changed in VaultAPI to support 1.13 and warn that it will be a challenge to make vaultAPI support all the old versions it does now in a single package. I already see some good work being done on forks of this project but they are still a mix of current material names and "legacy" which is still not really forward compatible. MD5 has stressed the legacy material layer will not be around in the future and adding api-version: 1.13 disables it. Sure, reflection could solve most of this but its a significant change from the simplicity concept vault was founded on. I greatly appreciate having separate classes for many of these things. The color varieties classes and heads/skulls naming conventions are a Mojang thing. Nothing we can do about that. Just make our own groups using spigots new Tag system.

**Comment by DoNotSpamPls** [comment]
Well, there are two real options, either make seperate versions of Vault/VaultAPI for 1.12 (and below) and 1.13+ or use hacky reflection to include both. Both suck, so this will probably be a hard decision for @Sleaker.

**Comment by Sleaker** [comment]
Not a hard decision really, the itemAPI is probably going away completely.

**Comment by Sleaker** [comment]
@woutwoot - the Item API was initially maintained due to having our own shop plugin also, it's been quite a long time since this was the case though. If people have a good way to handle the new changes to facilitate lookups I'd be willing to pull those in, but it'd be good to see what the options are (I haven't dug into the new item changes at all yet).

**Comment by Banbeucmas** [comment]
@Sleaker
I, now still use your ItemAPI on my plugin.
https://github.com/Banbeucmas/Oregen3/blob/master/src/main/java/me/banbeucmas/oregen3/utils/item/
I might do some contribution to the resouce if possible

**Comment by Sleaker** [comment]
ItemAPI has been removed it is obselesced by the entire new Material functionality. The plugin should be ready for 1.13.1
